spring.application.name=BloodDonation

spring.datasource.url=jdbc:postgresql://localhost:5432/blooddonationDB
spring.datasource.username=postgres
spring.datasource.password=bailly123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

